version: "3.9"
services:
    user_http_service:
        build:
            context: .
            dockerfile: ./docker/dockerfile_user_http
        image: go_blog_user_http_service
        environment:
            APP_NAME: "user_http_service"
        ports:
            - 80:80
        networks:
            - blog_realworld_network

    auth_grpc_service:
        build:
            context: .
            dockerfile: ./docker/dockerfile_auth_grpc
        image: go_blog_auth_grpc_service
        environment:
            APP_NAME: "auth_grpc_service"
        ports:
            - 5001:5001
        networks:
            - blog_realworld_network

networks:
    blog_realworld_network:
        driver: bridge
