version: "3.9"
services:
  user_service:
    build:
      context: .
      dockerfile: ./docker/dockerfile-user
    image: go-blog-user-service
    environment:
      APP_NAME: "user-service"
    ports:
      - 5001:5001
    networks:
      - blog_realworld_network

networks:
  blog_realworld_network:
    driver: bridge
